### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException (NO_SOURCE_FILE:0)

### ISSUE THREAD

**Issue by bjeanes** [weavejester/lein-beanstalk#17]
I couldn't get `lein-beanstalk` to work in a `compojure` project of mine. It was failing with the same exception as this.

To rule out my project or its dependencies, I created a new `noir` project to replicate the behavior. Note that `lein uberjar` works as expected and the application boots and runs as expected. Here's the steps to reproduce:

```
$ lein new noir footest
[ ... snip ... ]
$ cd footest
$ # add lein-beanstalk to :plugins or :dev-dependencies in project.clj
$ lein deps
[ ... snip ... ]
$ lein beanstalk info
Application 'footest' not found on AWS Elastic Beanstalk
3.153s total, 8.33s user, 0.44s system, 278% cpu
$ lein beanstalk deploy production
Compiling footest.server
Compilation succeeded.
Exception in thread "main" java.lang.NullPointerException (NO_SOURCE_FILE:0)
        at clojure.lang.Compiler.eval(Compiler.java:5440)
        at clojure.lang.Compiler.eval(Compiler.java:5391)
        at clojure.core$eval.invoke(core.clj:2382)
        at clojure.main$eval_opt.invoke(main.clj:235)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$script_opt.invoke(main.clj:270)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at clojure.lang.Var.invoke(Var.java:385)
        at clojure.lang.AFn.applyToHelper(AFn.java:185)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
        at clojure.core$namespace.invoke(core.clj:1252)
        at leiningen.ring.war$compile_servlet.invoke(war.clj:148)
        at leiningen.ring.uberwar$uberwar.invoke(uberwar.clj:47)
        at leiningen.beanstalk$deploy.invoke(beanstalk.clj:39)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.beanstalk$beanstalk.doInvoke(beanstalk.clj:126)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at clojure.lang.Var.invoke(Var.java:373)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$apply_task.invoke(core.clj:262)
        at leiningen.core$_main.doInvoke(core.clj:329)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$_main.invoke(core.clj:332)
        at user$eval42.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        ... 11 more
```

I tested it with Clojure 1.3.0 and Clojure 1.4.0 and my `lein` version is 1.7.1.

Let me know if you need any more information or if I have missed a step.

**Comment by bjeanes** [comment]
I realize from looking at this deeper that this is occurring from `lein ring uberwar` instead.

**Comment by bjeanes** [comment]
Ok... so for posterity:

You need to have the `:ring` key defined in your `project.clj`. Since my two projects were using `compojure` and `noir` instead of `ring` directly, I was booting a server directly by having my `-main` function call `run-jetty` and passing it the routes.

In the case of `compojure`, I created a handler based on my routes like so:

``` clojure
(ns my-project.routes 
  (:require [compojure.handler]
            [compojure.core :as compojure]))

(defroutes main-routes
  (GET "/" [] ...))

(def handler (compojure.handler/api main-routes))
```

Then in my `project.clj`, I added the following key-pair to the `(defproject ...)` call:

``` clojure
(defproject my-project "1.0.0-SNAPSHOT"
            :ring {:handler bungle-o.handler/handler}
            :dependencies [...]
            :... ...)
```

After that `lein ring uberwar` worked, as did `lein beanstalk deploy <env>``

**Comment by cemerick** [comment]
Yeah, the docs for lein-beanstalk should probably mention somewhere that it uses all of lein-ring's configuration as well. :-/

I've fixed that in the README now.  Thanks.
